version: '3'

services:
  web: # Flask
    build: .
    depends_on:
      es:
       condition: service_healthy
  
  es: # Elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - "discovery.type=single-node"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck: # Checks if the DB itself is up
      test: ["CMD", "curl", "-f" ,"localhost:9200"]
      interval: 10s
      retries: 5
  
  nginx: # Nginx
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf/conf.d:/etc/nginx/conf.d
      - ./templates/index.html:/app/html/index.html  
      #- ./static:/usr/share/nginx/html
    depends_on: # Make sure app is up first
      - web
volumes:
  esdata: