version: '3'

services:
  java-app: 
    build: .
    depends_on:
      sql-db:
        condition: service_healthy
    networks:
      - frontend
      - backend
    volumes:
      - lavagna_webapp:/app/lavagna

  sql-db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secretpass
    volumes:
      - db_data:/var/lib/mysql
      - ./lavagna.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-psecretpass"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend


  nginx:
    image: nginx:stable
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - ./nginx-conf/conf.d:/etc/nginx/conf.d
      - lavagna_webapp:/usr/share/nginx/html:rw
    depends_on:
      - java-app
    networks:
      - frontend

volumes:
  db_data:
  lavagna_webapp:

networks:
  frontend:
  backend:
